    mail.enabled=true
    mail.smtp.host=smtp.gmail.com
    mail.smtp.port=587
    mail.smtp.auth=true
    mail.smtp.starttls.enable=true
    mail.username=yaserbenhajla@gmail.com
    mail.password=wagf zvjp nxxi sgbw
mail.from=yaserbenhajla@gmail.com
mail.from.name=WellBalance
mail.default.recipient=yaserbenhajla@gmail.com
